server:
  port: 4000

spring:
  datasource:
    url: jdbc:h2:mem:budget_management?serverTimezone=Asia/Seoul;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    generate-ddl: true

  h2:
    console:
      enabled: true

security:
  jwt:
    token:
      secret-key: c3ByaW5nLWJvb3QtdGVzdC1zZWNyZXQta2V5 #test key
      access:
        expire-length: 3600000 #1시간
      refresh:
        expire-length: 1210000000 #14일
