spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/budget_management?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: ${MYSQL_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true

security:
  jwt:
    token:
      secret-key: c3ByaW5nLWJvb3QtdGVzdC1zZWNyZXQta2V5
      access:
        expire-length: 3600000
      refresh:
        expire-length: 1210000000