server:
  port: 4000

spring:
  datasource:
    url: jdbc:h2:mem:budget_management?serverTimezone=Asia/Seoul;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    generate-ddl: true

  h2:
    console:
      enabled: true
